<section class="wrapper" id="user-sign">
    <div class="container">
        <div class="row">
            <h1 class="text-center">Register your account</h1>
            <div class="col-lg-6 col-centered">
                <form data-action="<?php echo BASE_URL; ?>index.php?page=auth&action=doregister" method="post" enctype="multipart/form-data" class="register">
                    <label for="email">Email</label>
                    <input type="text" name="email" id="email" class="form-control" placeholder="Please, enter your e-mail" required="">

                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" class="form-control" placeholder="Please, enter your username" required="">

                    <label for="name">Full Name</label>
                    <input type="text" name="name" id="name" class="form-control" placeholder="Please, enter your fullname" required="">

                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="Please, enter your passsword" required="">

                    <button class="btn btn-lg btn-primary btn-block" type="submit">Register <i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
                </form>
            </div>
        </div>
    </div>
</section>